
development:
  adapter  : mysql2
  database : esimplify_development
  encoding : utf8
  username : root
  password :
  host     : localhost

test:
  adapter  : mysql2
  database : esimplify_test
  encoding : utf8
  username : root
  password :
  host     : localhost

production:
  adapter  : mysql2
  database : esimplify_production
  encoding : utf8
  username : spirit
  password : ghost0504
  host     : localhost
  reconnect: true